# Generated by Django 5.1.15 on 2026-06-01 06:01

import apps.messages_api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('templating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(default=apps.messages_api.models._new_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook')], max_length=16)),
                ('recipient', models.TextField()),
                ('rendered_subject', models.TextField(blank=True, default='')),
                ('rendered_body', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('priority', models.CharField(choices=[('high', 'High'), ('default', 'Default'), ('low', 'Low')], default='default', max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('dead', 'Dead')], default='queued', max_length=16)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='core.apikey')),
                ('template_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='templating.templateversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attempt_no', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(choices=[('success', 'Success'), ('transient_error', 'Transient error'), ('permanent_error', 'Permanent error')], max_length=24)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('smtp_code', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='messages_api.message')),
            ],
        ),
        migrations.CreateModel(
            name='DeadLetter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dead_letter', to='messages_api.message')),
            ],
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['status', 'scheduled_at'], name='message_status_sched_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='message_created_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient'], name='message_recipient_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('api_key', 'idempotency_key'), name='message_idempotency_unique'),
        ),
        migrations.AddIndex(
            model_name='deliveryattempt',
            index=models.Index(fields=['message', 'attempt_no'], name='delivery_attempt_msg_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryattempt',
            constraint=models.UniqueConstraint(fields=('message', 'attempt_no'), name='delivery_attempt_unique'),
        ),
        migrations.AddIndex(
            model_name='deadletter',
            index=models.Index(fields=['created_at'], name='dead_letter_created_idx'),
        ),
    ]
