# Generated by Django 5.1.15 on 2026-06-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('messages_api', '0001_initial'),
        ('templating', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(condition=models.Q(('status', 'queued')), fields=['scheduled_at'], name='message_queued_partial_idx'),
        ),
    ]
