# Generated by Django 5.1.15 on 2026-06-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('prefix', models.CharField(db_index=True, max_length=32)),
                ('hashed_secret', models.CharField(max_length=255)),
                ('rate_limit_per_min', models.PositiveIntegerField(default=100)),
                ('burst', models.PositiveIntegerField(default=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'indexes': [models.Index(fields=['is_active', 'revoked_at'], name='api_key_active_idx')],
            },
        ),
    ]
